defaults: &defaults
  twitter:
    consumer_key: urEGqLYxhKp7rrc9jDIUdOAWS
    consumer_secret: 1IahqWk4XPeOPbLDAm9rkcMPSMaMdUF7Ic4eYUcJDz1nLyDtYD

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
